# Generated by Django 6.0.6 on 2026-06-16 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_no', models.CharField(max_length=32, unique=True, verbose_name='户编号')),
                ('head_name', models.CharField(blank=True, max_length=64, verbose_name='户主姓名')),
                ('head_identity_number', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='户主身份证号码')),
                ('head_gender', models.CharField(blank=True, max_length=16, verbose_name='户主性别')),
                ('village_group', models.CharField(blank=True, max_length=64, verbose_name='村组')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='家庭地址')),
                ('household_type', models.CharField(blank=True, max_length=64, verbose_name='户属性')),
                ('account_type', models.CharField(blank=True, max_length=64, verbose_name='户口类型')),
                ('grid_name', models.CharField(blank=True, max_length=64, verbose_name='所属网格')),
                ('housing_type', models.CharField(blank=True, max_length=64, verbose_name='住房类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '户信息',
                'verbose_name_plural': '户信息',
                'ordering': ['household_no'],
            },
        ),
        migrations.CreateModel(
            name='ResidentImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('source_headers', models.JSONField(blank=True, default=list, verbose_name='源表头')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('imported', '已导入'), ('failed', '导入失败')], default='uploaded', max_length=16, verbose_name='状态')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='总行数')),
                ('imported_rows', models.PositiveIntegerField(default=0, verbose_name='导入行数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '居民导入批次',
                'verbose_name_plural': '居民导入批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, verbose_name='居民姓名')),
                ('gender', models.CharField(blank=True, max_length=16, verbose_name='性别')),
                ('identity_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='身份证号码')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('ethnicity', models.CharField(blank=True, max_length=32, verbose_name='民族')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='联系电话')),
                ('relation_to_head', models.CharField(blank=True, max_length=32, verbose_name='与户主关系')),
                ('village_group', models.CharField(blank=True, max_length=64, verbose_name='村组')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='家庭地址')),
                ('household_type', models.CharField(blank=True, max_length=64, verbose_name='户属性')),
                ('account_type', models.CharField(blank=True, max_length=64, verbose_name='户口类型')),
                ('grid_name', models.CharField(blank=True, max_length=64, verbose_name='所属网格')),
                ('political_status', models.CharField(blank=True, max_length=64, verbose_name='政治面貌')),
                ('marital_status', models.CharField(blank=True, max_length=32, verbose_name='婚姻状况')),
                ('health_status', models.CharField(blank=True, max_length=32, verbose_name='健康状态')),
                ('residency_status', models.CharField(blank=True, max_length=32, verbose_name='居住状态')),
                ('education_level', models.CharField(blank=True, max_length=32, verbose_name='文化程度')),
                ('occupation', models.CharField(blank=True, max_length=64, verbose_name='职业')),
                ('bank_account', models.CharField(blank=True, max_length=64, verbose_name='银行账号')),
                ('bank_name', models.CharField(blank=True, max_length=64, verbose_name='开户行')),
                ('military_status', models.CharField(blank=True, max_length=32, verbose_name='兵役状况')),
                ('status', models.CharField(blank=True, default='正常', max_length=32, verbose_name='状态')),
                ('is_household_head', models.BooleanField(default=False, verbose_name='是否户主')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='village_affairs.household', verbose_name='所属户')),
            ],
            options={
                'verbose_name': '居民信息',
                'verbose_name_plural': '居民信息',
                'ordering': ['id'],
            },
        ),
    ]
