# Generated by Django 6.0.6 on 2026-06-16 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('identity_number', models.CharField(db_index=True, max_length=32, verbose_name='身份证号')),
                ('village_group', models.CharField(blank=True, max_length=64, verbose_name='村组')),
                ('risk_level', models.CharField(choices=[('high', '高风险'), ('medium', '中风险'), ('low', '低风险')], default='low', max_length=16, verbose_name='风险等级')),
                ('warning_time', models.DateTimeField(auto_now_add=True, verbose_name='预警时间')),
                ('last_check_time', models.DateTimeField(blank=True, null=True, verbose_name='最近排查')),
                ('check_count', models.IntegerField(default=0, verbose_name='排查次数')),
                ('management_content', models.TextField(blank=True, verbose_name='预管内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_checks', to='village_affairs.resident', verbose_name='关联居民')),
            ],
            options={
                'verbose_name': '风险排查',
                'verbose_name_plural': '风险排查',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=16, verbose_name='性别')),
                ('identity_number', models.CharField(db_index=True, max_length=32, verbose_name='身份证号')),
                ('village_group', models.CharField(blank=True, max_length=64, verbose_name='村组')),
                ('work_status', models.CharField(choices=[('working', '在外务工'), ('returned', '已返乡')], default='working', max_length=16, verbose_name='务工状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('work_address', models.CharField(blank=True, max_length=255, verbose_name='务工地址')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='单位名称')),
                ('industry', models.CharField(blank=True, max_length=128, verbose_name='行业')),
                ('job_type', models.CharField(blank=True, max_length=128, verbose_name='工种')),
                ('special_group', models.CharField(choices=[('none', '无'), ('poverty', '贫困户'), ('disabled', '残疾人'), ('left_behind', '留守人员'), ('other', '其他')], default='none', max_length=32, verbose_name='特殊人群')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最近更新')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_info', to='village_affairs.resident', verbose_name='关联居民')),
            ],
            options={
                'verbose_name': '务工信息',
                'verbose_name_plural': '务工信息',
                'ordering': ['-created_at'],
            },
        ),
    ]
