# Generated by Django 6.0.6 on 2026-07-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0002_riskcheck_workinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinfo',
            name='resident',
        ),
        migrations.AddField(
            model_name='residentimportbatch',
            name='created_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='新增行数'),
        ),
        migrations.AddField(
            model_name='residentimportbatch',
            name='error_details',
            field=models.JSONField(blank=True, default=list, verbose_name='错误详情'),
        ),
        migrations.AddField(
            model_name='residentimportbatch',
            name='field_mapping',
            field=models.JSONField(blank=True, default=dict, verbose_name='字段映射'),
        ),
        migrations.AddField(
            model_name='residentimportbatch',
            name='invalid_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='无效行数'),
        ),
        migrations.AddField(
            model_name='residentimportbatch',
            name='updated_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='更新行数'),
        ),
        migrations.AddField(
            model_name='residentimportbatch',
            name='valid_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='有效行数'),
        ),
        migrations.AlterField(
            model_name='residentimportbatch',
            name='status',
            field=models.CharField(choices=[('uploaded', '已上传'), ('previewed', '已预览'), ('imported', '已导入'), ('failed', '导入失败')], default='uploaded', max_length=16, verbose_name='状态'),
        ),
        migrations.DeleteModel(
            name='RiskCheck',
        ),
        migrations.DeleteModel(
            name='WorkInfo',
        ),
    ]
