# Generated by Django 6.0.6 on 2026-07-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0003_remove_workinfo_resident_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrantWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('identity_number', models.CharField(db_index=True, max_length=32, verbose_name='身份证号码')),
                ('gender', models.CharField(blank=True, max_length=16, verbose_name='性别')),
                ('village_group', models.CharField(blank=True, max_length=64, verbose_name='村组')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='联系电话')),
                ('household_type', models.CharField(blank=True, max_length=64, verbose_name='户属性')),
                ('work_status', models.CharField(choices=[('在外务工', '在外务工'), ('已返乡', '已返乡')], default='在外务工', max_length=16, verbose_name='务工状态')),
                ('is_employed', models.BooleanField(default=True, verbose_name='是否就业')),
                ('work_area', models.CharField(blank=True, max_length=255, verbose_name='务工区域')),
                ('work_address', models.CharField(blank=True, max_length=255, verbose_name='务工地址')),
                ('work_industry', models.CharField(blank=True, max_length=128, verbose_name='行业')),
                ('work_type', models.CharField(blank=True, max_length=128, verbose_name='工种')),
                ('employer', models.CharField(blank=True, max_length=255, verbose_name='单位名称')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='预计返乡时间')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='实际返乡时间')),
                ('is_special_group', models.BooleanField(default=False, verbose_name='是否特殊人群')),
                ('month_income', models.CharField(blank=True, max_length=32, verbose_name='月收入')),
                ('year_income', models.CharField(blank=True, max_length=32, verbose_name='年收入')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migrant_worker', to='village_affairs.resident', verbose_name='关联居民')),
            ],
            options={
                'verbose_name': '务工信息',
                'verbose_name_plural': '务工信息',
                'ordering': ['-updated_at'],
            },
        ),
    ]
