# Generated by Django 6.0.6 on 2026-07-02 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0004_migrantworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('identity_number', models.CharField(db_index=True, max_length=32, verbose_name='身份证号')),
                ('head_name', models.CharField(blank=True, max_length=64, verbose_name='户主姓名')),
                ('head_identity_number', models.CharField(blank=True, max_length=32, verbose_name='户主证件号')),
                ('household_type', models.CharField(blank=True, max_length=64, verbose_name='户属性')),
                ('risk_level', models.CharField(blank=True, choices=[('高风险', '高风险'), ('中风险', '中风险'), ('低风险', '低风险')], max_length=16, verbose_name='风险等级')),
                ('warning_content', models.TextField(blank=True, max_length=2000, verbose_name='预警内容')),
                ('medical_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='医疗自付费用金额')),
                ('warning_time', models.DateField(verbose_name='预警时间')),
                ('alert_time', models.DateTimeField(auto_now_add=True, verbose_name='告警时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_checks', to='village_affairs.resident', verbose_name='关联居民')),
            ],
            options={
                'verbose_name': '风险排查',
                'verbose_name_plural': '风险排查',
                'ordering': ['-warning_time', '-id'],
            },
        ),
    ]
