# Generated by Django 6.0.6 on 2026-07-04 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0005_riskcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowIncomeImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('source_headers', models.JSONField(blank=True, default=list, verbose_name='源表头')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='字段映射')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('previewed', '已预览'), ('imported', '已导入'), ('failed', '导入失败')], default='uploaded', max_length=16, verbose_name='状态')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='总行数')),
                ('valid_rows', models.PositiveIntegerField(default=0, verbose_name='有效行数')),
                ('invalid_rows', models.PositiveIntegerField(default=0, verbose_name='无效行数')),
                ('imported_rows', models.PositiveIntegerField(default=0, verbose_name='导入行数')),
                ('created_rows', models.PositiveIntegerField(default=0, verbose_name='新增行数')),
                ('updated_rows', models.PositiveIntegerField(default=0, verbose_name='更新行数')),
                ('error_details', models.JSONField(blank=True, default=list, verbose_name='错误详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '低收入导入批次',
                'verbose_name_plural': '低收入导入批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskCheckImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('source_headers', models.JSONField(blank=True, default=list, verbose_name='源表头')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='字段映射')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('previewed', '已预览'), ('imported', '已导入'), ('failed', '导入失败')], default='uploaded', max_length=16, verbose_name='状态')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='总行数')),
                ('valid_rows', models.PositiveIntegerField(default=0, verbose_name='有效行数')),
                ('invalid_rows', models.PositiveIntegerField(default=0, verbose_name='无效行数')),
                ('imported_rows', models.PositiveIntegerField(default=0, verbose_name='导入行数')),
                ('created_rows', models.PositiveIntegerField(default=0, verbose_name='新增行数')),
                ('updated_rows', models.PositiveIntegerField(default=0, verbose_name='更新行数')),
                ('error_details', models.JSONField(blank=True, default=list, verbose_name='错误详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '风险排查导入批次',
                'verbose_name_plural': '风险排查导入批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LowIncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, verbose_name='居民姓名')),
                ('identity_number', models.CharField(db_index=True, max_length=32, verbose_name='身份证号')),
                ('gender', models.CharField(blank=True, max_length=16, verbose_name='性别')),
                ('ethnicity', models.CharField(blank=True, max_length=32, verbose_name='民族')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='联系电话')),
                ('head_name', models.CharField(blank=True, max_length=64, verbose_name='户主姓名')),
                ('relation_to_head', models.CharField(blank=True, max_length=32, verbose_name='与户主关系')),
                ('village_group', models.CharField(blank=True, max_length=64, verbose_name='村组')),
                ('policy_type', models.CharField(blank=True, max_length=64, verbose_name='享受政策类型')),
                ('benefit_level', models.CharField(blank=True, max_length=64, verbose_name='享受档次')),
                ('subsidy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='补贴金额')),
                ('subsidy_cycle', models.CharField(blank=True, max_length=64, verbose_name='补贴周期')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('household_member_count', models.PositiveIntegerField(default=0, verbose_name='全户人数')),
                ('beneficiary_count', models.PositiveIntegerField(default=1, verbose_name='享受人数')),
                ('household_month_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='户月金额')),
                ('status', models.CharField(choices=[('在享', '在享'), ('停享', '停享')], default='在享', max_length=16, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='low_income_records', to='village_affairs.household', verbose_name='关联家庭')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='low_income_records', to='village_affairs.resident', verbose_name='关联居民')),
            ],
            options={
                'verbose_name': '低收入人员',
                'verbose_name_plural': '低收入人员',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
