# Generated by Django 6.0.6 on 2026-07-05 05:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0006_lowincomeimportbatch_riskcheckimportbatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('source_headers', models.JSONField(blank=True, default=list, verbose_name='源表头')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='字段映射')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('previewed', '已预览'), ('imported', '已导入'), ('failed', '导入失败')], default='uploaded', max_length=16, verbose_name='状态')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='总行数')),
                ('valid_rows', models.PositiveIntegerField(default=0, verbose_name='有效行数')),
                ('invalid_rows', models.PositiveIntegerField(default=0, verbose_name='无效行数')),
                ('imported_rows', models.PositiveIntegerField(default=0, verbose_name='导入行数')),
                ('created_rows', models.PositiveIntegerField(default=0, verbose_name='新增行数')),
                ('updated_rows', models.PositiveIntegerField(default=0, verbose_name='更新行数')),
                ('error_details', models.JSONField(blank=True, default=list, verbose_name='错误详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '残疾人导入批次',
                'verbose_name_plural': '残疾人导入批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubsidyImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('source_headers', models.JSONField(blank=True, default=list, verbose_name='源表头')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='字段映射')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('previewed', '已预览'), ('imported', '已导入'), ('failed', '导入失败')], default='uploaded', max_length=16, verbose_name='状态')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='总行数')),
                ('valid_rows', models.PositiveIntegerField(default=0, verbose_name='有效行数')),
                ('invalid_rows', models.PositiveIntegerField(default=0, verbose_name='无效行数')),
                ('imported_rows', models.PositiveIntegerField(default=0, verbose_name='导入行数')),
                ('created_rows', models.PositiveIntegerField(default=0, verbose_name='新增行数')),
                ('updated_rows', models.PositiveIntegerField(default=0, verbose_name='更新行数')),
                ('error_details', models.JSONField(blank=True, default=list, verbose_name='错误详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '两项补贴导入批次',
                'verbose_name_plural': '两项补贴导入批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisabledPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('identity_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='身份证号')),
                ('gender', models.CharField(blank=True, max_length=16, verbose_name='性别')),
                ('ethnicity', models.CharField(blank=True, max_length=32, verbose_name='民族')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='联系电话')),
                ('village_group', models.CharField(blank=True, max_length=64, verbose_name='村组')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='家庭地址')),
                ('disability_type', models.CharField(blank=True, max_length=64, verbose_name='残疾类型')),
                ('disability_level', models.CharField(blank=True, max_length=32, verbose_name='残疾等级')),
                ('disability_card_number', models.CharField(blank=True, max_length=64, verbose_name='残疾证号')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='办证日期')),
                ('guardian_name', models.CharField(blank=True, max_length=64, verbose_name='监护人姓名')),
                ('guardian_phone', models.CharField(blank=True, max_length=32, verbose_name='监护人电话')),
                ('status', models.CharField(choices=[('有效', '有效'), ('停用', '停用')], default='有效', max_length=16, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disabled_people', to='village_affairs.household', verbose_name='关联家庭')),
                ('resident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disabled_profile', to='village_affairs.resident', verbose_name='关联居民')),
            ],
            options={
                'verbose_name': '残疾人信息',
                'verbose_name_plural': '残疾人信息',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubsidyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_year', models.PositiveIntegerField(default=2026, verbose_name='年度')),
                ('batch_name', models.CharField(blank=True, max_length=64, verbose_name='批次')),
                ('subsidy_type', models.CharField(choices=[('困难残疾人生活补贴', '困难残疾人生活补贴'), ('重度残疾人护理补贴', '重度残疾人护理补贴')], max_length=64, verbose_name='补贴类型')),
                ('full_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('identity_number', models.CharField(db_index=True, max_length=32, verbose_name='身份证号')),
                ('bank_account', models.CharField(blank=True, max_length=64, verbose_name='银行账号')),
                ('village_group', models.CharField(blank=True, max_length=64, verbose_name='村组')),
                ('household_population', models.PositiveIntegerField(default=1, verbose_name='家庭人口')),
                ('subsidy_item', models.CharField(blank=True, max_length=128, verbose_name='项目/事项')),
                ('subsidy_standard', models.CharField(blank=True, max_length=64, verbose_name='规格')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='单位')),
                ('declared_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='申报金额')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实发金额')),
                ('payment_status', models.CharField(choices=[('待发放', '待发放'), ('已发放', '已发放')], default='待发放', max_length=16, verbose_name='发放状态')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='发放日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('disabled_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidy_records', to='village_affairs.disabledperson', verbose_name='关联残疾人档案')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidy_records', to='village_affairs.household', verbose_name='关联家庭')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_records', to='village_affairs.resident', verbose_name='关联居民')),
            ],
            options={
                'verbose_name': '两项补贴记录',
                'verbose_name_plural': '两项补贴记录',
                'ordering': ['-grant_year', '-updated_at', '-id'],
            },
        ),
    ]
