# Generated by Django 6.0.6 on 2026-07-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0007_disabledimportbatch_subsidyimportbatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_title', models.CharField(default='村务管理系统', max_length=128, verbose_name='系统标题')),
                ('logo_mode', models.CharField(choices=[('image', '仅图片'), ('text', '仅文字'), ('both', '图片+文字')], default='both', max_length=16, verbose_name='Logo显示方式')),
                ('logo_text', models.CharField(blank=True, default='村务管理系统', max_length=128, verbose_name='Logo文字')),
                ('logo_image', models.TextField(blank=True, verbose_name='Logo图片')),
                ('favicon', models.TextField(blank=True, verbose_name='浏览器图标')),
                ('village_overview', models.TextField(blank=True, verbose_name='村情概况')),
                ('village_image', models.TextField(blank=True, verbose_name='村情概况图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '界面设置',
                'verbose_name_plural': '界面设置',
            },
        ),
    ]
