# Generated by Django 6.0.6 on 2026-07-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0008_uisettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uisettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='ui_settings/', verbose_name='浏览器图标'),
        ),
        migrations.AlterField(
            model_name='uisettings',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='ui_settings/', verbose_name='Logo图片'),
        ),
        migrations.AlterField(
            model_name='uisettings',
            name='village_image',
            field=models.ImageField(blank=True, null=True, upload_to='ui_settings/', verbose_name='村情概况图片'),
        ),
    ]
