# Generated by Django 6.0.6 on 2026-07-05 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0009_alter_uisettings_favicon_alter_uisettings_logo_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(choices=[('党(总)支部委员会', '党(总)支部委员会'), ('村居民委员会', '村居民委员会'), ('村务监督委员会', '村务监督委员会'), ('青年团妇组织', '青年团妇组织'), ('集体经济组织理事会', '集体经济组织理事会'), ('集体经济组织监事会', '集体经济组织监事会'), ('村民小组长', '村民小组长'), ('村民代表', '村民代表')], default='党(总)支部委员会', max_length=64, verbose_name='组织类型')),
                ('source', models.CharField(blank=True, default='居民档案', max_length=32, verbose_name='来源')),
                ('full_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('ethnicity', models.CharField(blank=True, max_length=32, verbose_name='民族')),
                ('gender', models.CharField(blank=True, max_length=16, verbose_name='性别')),
                ('identity_number', models.CharField(db_index=True, max_length=32, verbose_name='身份证号')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='家庭住址')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='联系电话')),
                ('position', models.CharField(blank=True, max_length=64, verbose_name='职务')),
                ('political_status', models.CharField(blank=True, max_length=64, verbose_name='政治面貌')),
                ('term_number', models.CharField(blank=True, max_length=32, verbose_name='届数')),
                ('term_start', models.DateField(blank=True, null=True, verbose_name='任期开始')),
                ('term_end', models.DateField(blank=True, null=True, verbose_name='任期结束')),
                ('status', models.CharField(choices=[('现任', '现任'), ('历届', '历届')], default='现任', max_length=16, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_members', to='village_affairs.household', verbose_name='关联家庭')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_memberships', to='village_affairs.resident', verbose_name='关联居民')),
            ],
            options={
                'verbose_name': '组织架构成员',
                'verbose_name_plural': '组织架构成员',
                'ordering': ['org_type', '-status', '-updated_at', '-id'],
            },
        ),
    ]
