# Generated by Django 6.0.6 on 2026-07-05 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0010_organizationmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('居民档案', '居民档案'), ('手工新增', '手工新增')], default='居民档案', max_length=16, verbose_name='来源')),
                ('full_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('identity_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='身份证号')),
                ('gender', models.CharField(blank=True, max_length=16, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('ethnicity', models.CharField(blank=True, max_length=32, verbose_name='民族')),
                ('education_level', models.CharField(blank=True, max_length=32, verbose_name='学历')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='现居住址')),
                ('member_type', models.CharField(choices=[('中共党员', '中共党员'), ('预备党员', '预备党员'), ('入党积极分子', '入党积极分子')], default='中共党员', max_length=16, verbose_name='人员类别')),
                ('join_party_date', models.DateField(blank=True, null=True, verbose_name='入党日期')),
                ('becoming_full_member_date', models.DateField(blank=True, null=True, verbose_name='转正日期')),
                ('party_branch', models.CharField(blank=True, max_length=64, verbose_name='所在党支部')),
                ('current_position', models.CharField(blank=True, max_length=64, verbose_name='当前职务')),
                ('monthly_party_fee', models.DecimalField(blank=True, decimal_places=2, default='10.00', max_digits=8, null=True, verbose_name='默认月党费')),
                ('status', models.CharField(choices=[('正常', '正常'), ('已转出', '已转出'), ('停止党籍', '停止党籍')], default='正常', max_length=16, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_members', to='village_affairs.household', verbose_name='关联家庭')),
                ('resident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_profile', to='village_affairs.resident', verbose_name='关联居民')),
            ],
            options={
                'verbose_name': '党员信息',
                'verbose_name_plural': '党员信息',
                'ordering': ['party_branch', 'full_name', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartyMemberPositionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=64, verbose_name='党组织')),
                ('position_name', models.CharField(max_length=64, verbose_name='职务名称')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否当前职务')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('party_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_records', to='village_affairs.partymember', verbose_name='党员')),
            ],
            options={
                'verbose_name': '党员任职记录',
                'verbose_name_plural': '党员任职记录',
                'ordering': ['-is_current', '-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartyMemberTransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('转入', '转入'), ('转出', '转出'), ('组织关系转接', '组织关系转接'), ('状态变更', '状态变更')], default='组织关系转接', max_length=32, verbose_name='流转类型')),
                ('transfer_date', models.DateField(verbose_name='流转日期')),
                ('from_branch', models.CharField(blank=True, max_length=64, verbose_name='转出组织')),
                ('to_branch', models.CharField(blank=True, max_length=64, verbose_name='转入组织')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='原因')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('party_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_records', to='village_affairs.partymember', verbose_name='党员')),
            ],
            options={
                'verbose_name': '党员流转记录',
                'verbose_name_plural': '党员流转记录',
                'ordering': ['-transfer_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartyFeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_year', models.PositiveIntegerField(verbose_name='年度')),
                ('fee_month', models.PositiveIntegerField(verbose_name='月份')),
                ('amount_due', models.DecimalField(decimal_places=2, default='0.00', max_digits=8, verbose_name='应缴金额')),
                ('amount_paid', models.DecimalField(decimal_places=2, default='0.00', max_digits=8, verbose_name='实缴金额')),
                ('payment_status', models.CharField(choices=[('待缴纳', '待缴纳'), ('已缴纳', '已缴纳')], default='待缴纳', max_length=16, verbose_name='缴纳状态')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='缴纳日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('party_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='village_affairs.partymember', verbose_name='党员')),
            ],
            options={
                'verbose_name': '党费缴纳记录',
                'verbose_name_plural': '党费缴纳记录',
                'ordering': ['-fee_year', '-fee_month', 'party_member__full_name', '-id'],
                'constraints': [models.UniqueConstraint(fields=('party_member', 'fee_year', 'fee_month'), name='unique_party_fee_month')],
            },
        ),
    ]
