# Generated by Django 6.0.6 on 2026-07-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0011_partymember_partymemberpositionrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('birthday', '生日提醒'), ('party_fee', '党费提醒')], default='birthday', max_length=16, verbose_name='规则分类')),
                ('rule_name', models.CharField(max_length=64, verbose_name='规则名称')),
                ('age_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄条件')),
                ('remind_days', models.PositiveIntegerField(default=0, verbose_name='提前提醒天数')),
                ('reminder_time', models.TimeField(blank=True, null=True, verbose_name='提醒时间')),
                ('reminder_day', models.PositiveIntegerField(blank=True, null=True, verbose_name='提醒日期')),
                ('is_month_end', models.BooleanField(default=False, verbose_name='是否月底提醒')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '提醒规则',
                'verbose_name_plural': '提醒规则',
                'ordering': ['category', '-is_enabled', 'rule_name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TodoReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('reminder_type', models.CharField(choices=[('任务', '任务'), ('生日', '生日'), ('事件', '事件'), ('系统', '系统')], default='任务', max_length=16, verbose_name='类型')),
                ('progress', models.CharField(choices=[('未开始', '未开始'), ('处理中', '处理中'), ('已完成', '已完成')], default='未开始', max_length=16, verbose_name='进度')),
                ('reminder_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='提醒时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('source_type', models.CharField(choices=[('manual', '手工创建'), ('birthday_rule', '生日规则'), ('party_fee_rule', '党费规则')], default='manual', max_length=32, verbose_name='来源类型')),
                ('source_identifier', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='来源唯一标识')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '待办提醒',
                'verbose_name_plural': '待办提醒',
                'ordering': ['is_read', 'reminder_at', '-created_at', '-id'],
            },
        ),
    ]
