# Generated by Django 6.0.6 on 2026-07-05 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0012_reminderrule_todoreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('source_headers', models.JSONField(blank=True, default=list, verbose_name='源表头')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='字段映射')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('previewed', '已预览'), ('imported', '已导入'), ('failed', '导入失败')], default='uploaded', max_length=16, verbose_name='状态')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='总行数')),
                ('valid_rows', models.PositiveIntegerField(default=0, verbose_name='有效行数')),
                ('invalid_rows', models.PositiveIntegerField(default=0, verbose_name='无效行数')),
                ('imported_rows', models.PositiveIntegerField(default=0, verbose_name='导入行数')),
                ('created_rows', models.PositiveIntegerField(default=0, verbose_name='新增行数')),
                ('updated_rows', models.PositiveIntegerField(default=0, verbose_name='更新行数')),
                ('error_details', models.JSONField(blank=True, default=list, verbose_name='错误详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目台账导入批次',
                'verbose_name_plural': '项目台账导入批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(db_index=True, max_length=128, verbose_name='项目名称')),
                ('project_source', models.CharField(blank=True, choices=[('乡村振兴项目库', '乡村振兴项目库'), ('财政衔接资金项目库', '财政衔接资金项目库'), ('行业部门项目库', '行业部门项目库'), ('其他来源', '其他来源')], max_length=64, verbose_name='项目库来源')),
                ('project_type', models.CharField(blank=True, choices=[('基础设施', '基础设施'), ('产业发展', '产业发展'), ('社会事业', '社会事业'), ('生态环境', '生态环境')], max_length=32, verbose_name='项目类型')),
                ('secondary_type', models.CharField(blank=True, max_length=64, verbose_name='二级类型')),
                ('project_status', models.CharField(choices=[('规划中', '规划中'), ('实施中', '实施中'), ('已完成', '已完成'), ('已终止', '已终止')], default='规划中', max_length=32, verbose_name='项目状态')),
                ('planning_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='规划年度')),
                ('implementation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='实施年度')),
                ('included_in_plan', models.BooleanField(default=False, verbose_name='纳入计划')),
                ('total_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='项目预算总投资(万元)')),
                ('settled_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='结算金额(万元)')),
                ('audited_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='决算审计金额(万元)')),
                ('responsible_person', models.CharField(blank=True, max_length=64, verbose_name='督护人/责任人')),
                ('project_location', models.CharField(blank=True, max_length=255, verbose_name='项目地点')),
                ('project_description', models.TextField(blank=True, verbose_name='项目描述')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目台账',
                'verbose_name_plural': '项目台账',
                'ordering': ['-implementation_year', '-updated_at', '-id'],
            },
        ),
    ]
