# Generated by Django 6.0.6 on 2026-07-07 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0015_publicjobimportbatch_publicjobrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareObjectImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('source_headers', models.JSONField(blank=True, default=list, verbose_name='源表头')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='字段映射')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('previewed', '已预览'), ('imported', '已导入'), ('failed', '导入失败')], default='uploaded', max_length=16, verbose_name='状态')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='总行数')),
                ('valid_rows', models.PositiveIntegerField(default=0, verbose_name='有效行数')),
                ('invalid_rows', models.PositiveIntegerField(default=0, verbose_name='无效行数')),
                ('imported_rows', models.PositiveIntegerField(default=0, verbose_name='导入行数')),
                ('created_rows', models.PositiveIntegerField(default=0, verbose_name='新增行数')),
                ('updated_rows', models.PositiveIntegerField(default=0, verbose_name='更新行数')),
                ('error_details', models.JSONField(blank=True, default=list, verbose_name='错误详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '关爱对象导入批次',
                'verbose_name_plural': '关爱对象导入批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('identity_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='身份证号')),
                ('gender', models.CharField(blank=True, max_length=16, verbose_name='性别')),
                ('ethnicity', models.CharField(blank=True, max_length=32, verbose_name='民族')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='联系电话')),
                ('village_group', models.CharField(blank=True, max_length=64, verbose_name='村组')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='家庭地址')),
                ('care_type', models.CharField(blank=True, max_length=64, verbose_name='关爱类型')),
                ('care_level', models.CharField(blank=True, max_length=64, verbose_name='关爱等级')),
                ('caregiver_name', models.CharField(blank=True, max_length=64, verbose_name='关爱人员')),
                ('caregiver_phone', models.CharField(blank=True, max_length=32, verbose_name='联系方式')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_objects', to='village_affairs.household', verbose_name='关联家庭')),
                ('resident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_object_profile', to='village_affairs.resident', verbose_name='关联居民')),
            ],
            options={
                'verbose_name': '关爱对象',
                'verbose_name_plural': '关爱对象',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
