# Generated by Django 6.0.6 on 2026-07-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0016_careobjectimportbatch_careobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='档案编号')),
                ('dispute_type', models.CharField(max_length=64, verbose_name='纠纷类型')),
                ('status', models.CharField(choices=[('进行中', '进行中'), ('已调解', '已调解'), ('调解失败', '调解失败'), ('已归档', '已归档')], default='进行中', max_length=16, verbose_name='状态')),
                ('application_date', models.DateField(blank=True, null=True, verbose_name='申请日期')),
                ('occurrence_date', models.DateField(blank=True, null=True, verbose_name='发生日期')),
                ('occurrence_location', models.CharField(blank=True, max_length=255, verbose_name='发生地点')),
                ('applicants', models.JSONField(blank=True, default=list, verbose_name='申请人信息')),
                ('respondents', models.JSONField(blank=True, default=list, verbose_name='被申请人信息')),
                ('dispute_summary', models.TextField(blank=True, verbose_name='纠纷概述')),
                ('application_requests', models.JSONField(blank=True, default=list, verbose_name='申请事项')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '人民调解档案',
                'verbose_name_plural': '人民调解档案',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
