# Generated by Django 6.0.6 on 2026-07-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0019_farmlandimportbatch_farmlandrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='小组名称')),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='land_maps/', verbose_name='高清图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '村民小组',
                'verbose_name_plural': '村民小组',
                'ordering': ['id'],
            },
        ),
    ]
