# Generated by Django 6.0.6 on 2026-07-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0021_role_systemuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemActivation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, verbose_name='激活码')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='激活时间')),
                ('expire_at', models.DateTimeField(verbose_name='到期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '系统激活',
                'verbose_name_plural': '系统激活',
                'db_table': 'village_system_activation',
                'ordering': ['-activated_at'],
            },
        ),
    ]
