# Generated by Django 6.0.6 on 2026-07-24 14:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_affairs', '0022_systemactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrantworker',
            name='full_name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='partyfeerecord',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='应缴金额'),
        ),
        migrations.AlterField(
            model_name='partyfeerecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='实缴金额'),
        ),
        migrations.AlterField(
            model_name='partymember',
            name='monthly_party_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10.00'), max_digits=8, null=True, verbose_name='默认月党费'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='full_name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='居民姓名'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='village_group',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='村组'),
        ),
    ]
