from django.urls import path, re_path

from . import views
from .views import (
    frontend_app,
    auth_login_view,
    auth_logout_view,
    auth_status_view,
    population_age_structure,
    resident_collection,
    resident_delete,
    resident_detail,
    resident_error_report,
    resident_export,
    resident_household_summary,
    resident_import_commit,
    resident_import_preview,
    resident_import_upload,
    resident_options,
    resident_prefill,
    residents_by_age_group,
    system_status,
    migrant_workers_list,
    migrant_stats,
    employment_trend,
    migrant_worker_create,
    migrant_worker_detail,
    list_risk_checks_view,
    risk_check_create_view,
    risk_check_delete_view,
    risk_check_import_upload_view,
    risk_check_import_preview_view,
    risk_check_import_commit_view,
    risk_check_error_report_view,
    low_income_list_view,
    low_income_household_view,
    low_income_create_view,
    low_income_detail_view,
    low_income_bulk_delete_view,
    low_income_export_view,
    low_income_import_upload_view,
    low_income_import_preview_view,
    low_income_import_commit_view,
    low_income_error_report_view,
    disabled_list_view,
    disabled_create_view,
    disabled_detail_view,
    disabled_bulk_delete_view,
    disabled_export_view,
    disabled_import_upload_view,
    disabled_import_preview_view,
    disabled_import_commit_view,
    disabled_error_report_view,
    organization_member_list_view,
    organization_member_create_view,
    organization_member_detail_view,
    organization_member_bulk_delete_view,
    organization_member_export_view,
    party_member_list_view,
    party_member_create_view,
    party_member_detail_view,
    party_member_bulk_delete_view,
    party_member_export_view,
    party_fee_list_view,
    party_fee_generate_view,
    party_fee_detail_view,
    party_fee_mark_paid_view,
    party_fee_export_view,
    public_job_list_view,
    public_job_create_view,
    public_job_detail_view,
    public_job_export_view,
    public_job_import_upload_view,
    public_job_import_preview_view,
    public_job_import_commit_view,
    public_job_error_report_view,
    care_object_list_view,
    care_object_create_view,
    care_object_detail_view,
    care_object_bulk_delete_view,
    care_object_export_view,
    care_object_import_upload_view,
    care_object_import_preview_view,
    care_object_import_commit_view,
    care_object_error_report_view,
    mediation_next_archive_number_view,
    mediation_list_view,
    mediation_create_view,
    mediation_detail_view,
    mediation_export_view,
    mediation_trend_view,
    mediation_application_document_view,
    project_list_view,
    project_create_view,
    project_detail_view,
    project_export_view,
    project_import_upload_view,
    project_import_preview_view,
    project_import_commit_view,
    project_error_report_view,
    farmland_list_view,
    farmland_household_view,
    farmland_export_view,
    farmland_import_upload_view,
    farmland_import_preview_view,
    farmland_import_commit_view,
    farmland_error_report_view,
    subsidy_list_view,
    subsidy_create_view,
    subsidy_detail_view,
    subsidy_bulk_delete_view,
    subsidy_export_view,
    subsidy_import_upload_view,
    subsidy_import_preview_view,
    subsidy_import_commit_view,
    subsidy_error_report_view,
    todo_bulk_delete_view,
    todo_bulk_read_view,
    todo_create_view,
    todo_detail_view,
    todo_list_view,
    todo_mark_all_read_view,
    todo_summary_view,
    reminder_rule_list_view,
    reminder_rule_create_view,
    reminder_rule_detail_view,
    operation_log_cleanup_view,
    operation_log_list_view,
    database_backup_create_view,
    database_backup_detail_view,
    database_backup_download_view,
    database_backup_list_view,
    database_backup_restore_view,
    database_backup_upload_restore_view,
    database_clear_all_view,
    ui_settings_view,
    about_view,
)

app_name = 'village_affairs'

urlpatterns = [
    path('api/system/status/', system_status, name='api_system_status'),
    path('api/settings/ui/', ui_settings_view, name='api_ui_settings'),
    path('api/operation-logs/', operation_log_list_view, name='api_operation_log_list'),
    path('api/operation-logs/cleanup/', operation_log_cleanup_view, name='api_operation_log_cleanup'),
    path('api/data-security/backups/', database_backup_list_view, name='api_database_backup_list'),
    path('api/data-security/backups/create/', database_backup_create_view, name='api_database_backup_create'),
    path('api/data-security/backups/restore/upload/', database_backup_upload_restore_view, name='api_database_backup_upload_restore'),
    path('api/data-security/backups/<int:record_id>/download/', database_backup_download_view, name='api_database_backup_download'),
    path('api/data-security/backups/<int:record_id>/restore/', database_backup_restore_view, name='api_database_backup_restore'),
    path('api/data-security/backups/<int:record_id>/', database_backup_detail_view, name='api_database_backup_detail'),
    path('api/data-security/backups/clear-all/', database_clear_all_view, name='api_database_clear_all'),
    path('api/residents/options/', resident_options, name='api_resident_options'),
    path('api/residents/prefill/', resident_prefill, name='api_resident_prefill'),
    path('api/residents/', resident_collection, name='api_resident_collection'),
    path('api/residents/export/', resident_export, name='api_resident_export'),
    path('api/residents/households/', resident_household_summary, name='api_resident_households'),
    path('api/residents/import/upload/', resident_import_upload, name='api_resident_import_upload'),
    path('api/residents/import/preview/', resident_import_preview, name='api_resident_import_preview'),
    path('api/residents/import/commit/', resident_import_commit, name='api_resident_import_commit'),
    path('api/residents/<int:resident_id>/', resident_detail, name='api_resident_detail'),
    path('api/residents/<int:resident_id>/delete/', resident_delete, name='api_resident_delete'),
    path('api/residents/bulk-delete/', views.resident_bulk_delete, name='api_resident_bulk_delete'),
    path('api/residents/import/<uuid:batch_id>/error-report/', resident_error_report, name='api_resident_error_report'),
    path('api/population/age-structure/', population_age_structure, name='api_population_age_structure'),
    path('api/residents/age-group/<str:age_group>/', residents_by_age_group, name='api_residents_by_age_group'),
    path('api/migrant-workers/', migrant_workers_list, name='api_migrant_workers_list'),
    path('api/migrant-workers/bulk-delete/', views.migrant_worker_bulk_delete, name='api_migrant_worker_bulk_delete'),
    path('api/migrant-workers/stats/', migrant_stats, name='api_migrant_stats'),
    path('api/migrant-workers/trend/', employment_trend, name='api_employment_trend'),
    path('api/migrant-workers/create/', migrant_worker_create, name='api_migrant_worker_create'),
    path('api/migrant-workers/<int:worker_id>/', migrant_worker_detail, name='api_migrant_worker_detail'),
    path('api/risk-checks/', list_risk_checks_view, name='api_list_risk_checks'),
    path('api/risk-checks/create/', risk_check_create_view, name='api_risk_check_create'),
    path('api/risk-checks/<int:risk_id>/delete/', risk_check_delete_view, name='api_risk_check_delete'),
    path('api/risk-checks/bulk-delete/', views.risk_check_bulk_delete, name='api_risk_check_bulk_delete'),
    path('api/risk-checks/import/upload/', risk_check_import_upload_view, name='api_risk_check_import_upload'),
    path('api/risk-checks/import/preview/', risk_check_import_preview_view, name='api_risk_check_import_preview'),
    path('api/risk-checks/import/commit/', risk_check_import_commit_view, name='api_risk_check_import_commit'),
    path('api/risk-checks/import/<uuid:batch_id>/error-report/', risk_check_error_report_view, name='api_risk_check_error_report'),
    path('api/disabled/', disabled_list_view, name='api_disabled_list'),
    path('api/disabled/create/', disabled_create_view, name='api_disabled_create'),
    path('api/disabled/<int:record_id>/', disabled_detail_view, name='api_disabled_detail'),
    path('api/disabled/bulk-delete/', disabled_bulk_delete_view, name='api_disabled_bulk_delete'),
    path('api/disabled/export/', disabled_export_view, name='api_disabled_export'),
    path('api/disabled/import/upload/', disabled_import_upload_view, name='api_disabled_import_upload'),
    path('api/disabled/import/preview/', disabled_import_preview_view, name='api_disabled_import_preview'),
    path('api/disabled/import/commit/', disabled_import_commit_view, name='api_disabled_import_commit'),
    path('api/disabled/import/<uuid:batch_id>/error-report/', disabled_error_report_view, name='api_disabled_error_report'),
    path('api/org-structure/', organization_member_list_view, name='api_organization_member_list'),
    path('api/org-structure/create/', organization_member_create_view, name='api_organization_member_create'),
    path('api/org-structure/<int:record_id>/', organization_member_detail_view, name='api_organization_member_detail'),
    path('api/org-structure/bulk-delete/', organization_member_bulk_delete_view, name='api_organization_member_bulk_delete'),
    path('api/org-structure/export/', organization_member_export_view, name='api_organization_member_export'),
    path('api/party-members/', party_member_list_view, name='api_party_member_list'),
    path('api/party-members/create/', party_member_create_view, name='api_party_member_create'),
    path('api/party-members/<int:record_id>/', party_member_detail_view, name='api_party_member_detail'),
    path('api/party-members/bulk-delete/', party_member_bulk_delete_view, name='api_party_member_bulk_delete'),
    path('api/party-members/export/', party_member_export_view, name='api_party_member_export'),
    path('api/party-fees/', party_fee_list_view, name='api_party_fee_list'),
    path('api/party-fees/generate/', party_fee_generate_view, name='api_party_fee_generate'),
    path('api/party-fees/export/', party_fee_export_view, name='api_party_fee_export'),
    path('api/party-fees/<int:record_id>/', party_fee_detail_view, name='api_party_fee_detail'),
    path('api/party-fees/<int:record_id>/mark-paid/', party_fee_mark_paid_view, name='api_party_fee_mark_paid'),
    path('api/projects/', project_list_view, name='api_project_list'),
    path('api/projects/create/', project_create_view, name='api_project_create'),
    path('api/projects/export/', project_export_view, name='api_project_export'),
    path('api/projects/import/upload/', project_import_upload_view, name='api_project_import_upload'),
    path('api/projects/import/preview/', project_import_preview_view, name='api_project_import_preview'),
    path('api/projects/import/commit/', project_import_commit_view, name='api_project_import_commit'),
    path('api/projects/import/<uuid:batch_id>/error-report/', project_error_report_view, name='api_project_error_report'),
    path('api/projects/<int:record_id>/', project_detail_view, name='api_project_detail'),
    path('api/farmland/', farmland_list_view, name='api_farmland_list'),
    path('api/farmland/households/', farmland_household_view, name='api_farmland_household'),
    path('api/farmland/export/', farmland_export_view, name='api_farmland_export'),
    path('api/farmland/import/upload/', farmland_import_upload_view, name='api_farmland_import_upload'),
    path('api/farmland/import/preview/', farmland_import_preview_view, name='api_farmland_import_preview'),
    path('api/farmland/import/commit/', farmland_import_commit_view, name='api_farmland_import_commit'),
    path('api/farmland/import/<uuid:batch_id>/error-report/', farmland_error_report_view, name='api_farmland_error_report'),
    path('api/public-jobs/', public_job_list_view, name='api_public_job_list'),
    path('api/public-jobs/create/', public_job_create_view, name='api_public_job_create'),
    path('api/public-jobs/<int:record_id>/', public_job_detail_view, name='api_public_job_detail'),
    path('api/public-jobs/export/', public_job_export_view, name='api_public_job_export'),
    path('api/public-jobs/import/upload/', public_job_import_upload_view, name='api_public_job_import_upload'),
    path('api/public-jobs/import/preview/', public_job_import_preview_view, name='api_public_job_import_preview'),
    path('api/public-jobs/import/commit/', public_job_import_commit_view, name='api_public_job_import_commit'),
    path('api/public-jobs/import/<uuid:batch_id>/error-report/', public_job_error_report_view, name='api_public_job_error_report'),
    path('api/care-objects/', care_object_list_view, name='api_care_object_list'),
    path('api/care-objects/create/', care_object_create_view, name='api_care_object_create'),
    path('api/care-objects/<int:record_id>/', care_object_detail_view, name='api_care_object_detail'),
    path('api/care-objects/bulk-delete/', care_object_bulk_delete_view, name='api_care_object_bulk_delete'),
    path('api/care-objects/export/', care_object_export_view, name='api_care_object_export'),
    path('api/care-objects/import/upload/', care_object_import_upload_view, name='api_care_object_import_upload'),
    path('api/care-objects/import/preview/', care_object_import_preview_view, name='api_care_object_import_preview'),
    path('api/care-objects/import/commit/', care_object_import_commit_view, name='api_care_object_import_commit'),
    path('api/care-objects/import/<uuid:batch_id>/error-report/', care_object_error_report_view, name='api_care_object_error_report'),
    path('api/mediations/next-archive-number/', mediation_next_archive_number_view, name='api_mediation_next_archive_number'),
    path('api/mediations/trend/', mediation_trend_view, name='api_mediation_trend'),
    path('api/mediations/', mediation_list_view, name='api_mediation_list'),
    path('api/mediations/create/', mediation_create_view, name='api_mediation_create'),
    path('api/mediations/export/', mediation_export_view, name='api_mediation_export'),
    path('api/mediations/<int:record_id>/', mediation_detail_view, name='api_mediation_detail'),
    path('api/mediations/<int:record_id>/application-document/', mediation_application_document_view, name='api_mediation_application_document'),
    path('api/todos/', todo_list_view, name='api_todo_list'),
    path('api/todos/summary/', todo_summary_view, name='api_todo_summary'),
    path('api/todos/create/', todo_create_view, name='api_todo_create'),
    path('api/todos/bulk-delete/', todo_bulk_delete_view, name='api_todo_bulk_delete'),
    path('api/todos/bulk-read/', todo_bulk_read_view, name='api_todo_bulk_read'),
    path('api/todos/mark-all-read/', todo_mark_all_read_view, name='api_todo_mark_all_read'),
    path('api/todos/<int:record_id>/', todo_detail_view, name='api_todo_detail'),
    path('api/reminder-rules/', reminder_rule_list_view, name='api_reminder_rule_list'),
    path('api/reminder-rules/create/', reminder_rule_create_view, name='api_reminder_rule_create'),
    path('api/reminder-rules/<int:record_id>/', reminder_rule_detail_view, name='api_reminder_rule_detail'),
    path('api/subsidies/', subsidy_list_view, name='api_subsidy_list'),
    path('api/subsidies/create/', subsidy_create_view, name='api_subsidy_create'),
    path('api/subsidies/<int:record_id>/', subsidy_detail_view, name='api_subsidy_detail'),
    path('api/subsidies/bulk-delete/', subsidy_bulk_delete_view, name='api_subsidy_bulk_delete'),
    path('api/subsidies/export/', subsidy_export_view, name='api_subsidy_export'),
    path('api/subsidies/import/upload/', subsidy_import_upload_view, name='api_subsidy_import_upload'),
    path('api/subsidies/import/preview/', subsidy_import_preview_view, name='api_subsidy_import_preview'),
    path('api/subsidies/import/commit/', subsidy_import_commit_view, name='api_subsidy_import_commit'),
    path('api/subsidies/import/<uuid:batch_id>/error-report/', subsidy_error_report_view, name='api_subsidy_error_report'),
    path('api/low-income/', low_income_list_view, name='api_low_income_list'),
    path('api/low-income/households/', low_income_household_view, name='api_low_income_household'),
    path('api/low-income/create/', low_income_create_view, name='api_low_income_create'),
    path('api/low-income/<int:record_id>/', low_income_detail_view, name='api_low_income_detail'),
    path('api/low-income/bulk-delete/', low_income_bulk_delete_view, name='api_low_income_bulk_delete'),
    path('api/low-income/export/', low_income_export_view, name='api_low_income_export'),
    path('api/low-income/import/upload/', low_income_import_upload_view, name='api_low_income_import_upload'),
    path('api/low-income/import/preview/', low_income_import_preview_view, name='api_low_income_import_preview'),
    path('api/low-income/import/commit/', low_income_import_commit_view, name='api_low_income_import_commit'),
    path('api/low-income/import/<uuid:batch_id>/error-report/', low_income_error_report_view, name='api_low_income_error_report'),
    
    path('api/village-groups/', views.village_group_collection),
    path('api/village-groups/<int:group_id>/', views.village_group_detail),
    
    # User and Role Management
    path('api/roles/', views.role_list_create, name='role_list_create'),
    path('api/roles/<int:pk>/', views.role_detail, name='role_detail'),
    path('api/users/', views.user_list_create, name='user_list_create'),
    path('api/users/<int:pk>/', views.user_detail, name='user_detail'),
    
    # System shutdown and Activation
    path('api/system/shutdown/', views.system_shutdown, name='system_shutdown'),
    path('api/activation/', views.activation_view, name='activation'),
    path('api/system/about/', about_view, name='api_about'),
    
    # Authentication
    path('api/auth/login/', auth_login_view, name='api_auth_login'),
    path('api/auth/status/', auth_status_view, name='api_auth_status'),
    path('api/auth/logout/', auth_logout_view, name='api_auth_logout'),
    
    re_path(r'^(?!admin/|api/|media/).*$', frontend_app, name='frontend_app'),  
]
